// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "extremis",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Extremis",
            targets: ["AppModule"],
            bundleIdentifier: "com.danielkim.extremis",
            teamIdentifier: "29R3JXG54K",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Assets.xcassets"),
                .process("ecoli.png"),
                .process("drosophila.png"),
                .process("celegans.png"),
                .process("reef_coral.png"),
                .process("desert_beetle.png"),
                .process("antarctic_icefish.png"),
                .process("tardigrade.png"),
                .process("pompeii_worm.png"),
                .process("saharan_silver_ant.png"),
                .process("wood_frog.png"),
            ]
        )
    ],
    swiftLanguageModes: [.v6]
)
